// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfkhxepgfxoynarrbqof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRma2h4ZXBnZnhveW5hcnJicW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDQ2OTIsImV4cCI6MjA2ODUyMDY5Mn0.e7MyStg2D02lqRWX1cVfTJ6fRsajj9HAmtgm9Fxr5BA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});